# Cross.toml - 跨平台编译配置
# 使用 Podman 作为容器引擎: export CROSS_CONTAINER_ENGINE=podman

[build.env]
passthrough = ["GITHUB_TOKEN", "CARGO_REGISTRY_TOKEN", "RUST_LOG"]

# macOS 目标配置 - 需要特殊的交叉编译工具链
# 在 Windows 上使用 Podman/Docker 交叉编译 macOS 目标较为复杂
# 建议在 macOS 机器上直接编译，或使用 GitHub Actions
# [target.x86_64-apple-darwin]
# [target.aarch64-apple-darwin]

# Linux ARM64 配置
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install -y libssl-dev:arm64 pkg-config",
]

# 其他架构的镜像配置可以在需要时添加
[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:edge"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:edge"
