# Rust formatting configuration for Tidepool project

# Code style
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Function formatting
fn_params_layout = "Tall"

# Miscellaneous
use_small_heuristics = "Max"

# Stable features only
newline_style = "Auto"
use_field_init_shorthand = true
force_explicit_abi = true
